services:
  # --- Database ---
  db:
    image: mysql:8.4
    restart: always
    # env_file:
    #   ./mySQL/.env
    environment:
      MYSQL_ROOT_PASSWORD: R007_p455W0rd_1s_C00l#1919
      MYSQL_DATABASE: tutoring_db
      MYSQL_USER: tutoring_user
      MYSQL_PASSWORD: 4n0TH3r_7u70Ring_p455W0rd#1337
    volumes:
      - mysql_data:/var/lib/mysql
      # UPDATED PATHS BELOW:
      - ./mySQL/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mySQL/migration.sql:/docker-entrypoint-initdb.d/migration.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  # --- Spring Boot Backend ---
  backend:
    build: ./backend
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  proxy:
    build: ./convert_frontend
    restart: on-failure
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network: